### ISSUE TITLE
Auth MVP Review

### ISSUE THREAD

**Issue by thedaebu** [thedaebu/reallysmart#7]
Hey Dane, I am ready for my auth MVP review. 
https://really-smart.herokuapp.com/#/
Thanks for all your help.

**Comment by danemauland** [comment]
Great work on your styling! I have relatively few corrections:

# Splash
## Header
Search icon is too large. Also, consider using FontAwesome or ReactIcons for something like this instead of using an image
## Navbar
Revisit how these are spaced out. At least on my browser, these aren't even close to how genius has their navbar spaced out. Let me know if you're seeing it as different.
## Body
Throw in placeholder values for the viewing and view totals
Add/style a (currently) non-functional LOAD MORE button

# Sign Up
Display the navbar here too (just use the same one for your splash page, it's close enough)
Extend the black background all the way to the bottom of the browser
Font weight on labels and on errors looks too light
Missing header color and some version of "and show off your genius"

**Comment by thedaebu** [comment]
I was able to make all the adjustments.
