### ISSUE TITLE
Annotations MVP Review

### ISSUE THREAD

**Issue by thedaebu** [thedaebu/reallysmart#9]
Hi Dane. I am ready for my annotations MVP review. Thank you for all your help!

**Comment by danemauland** [comment]
Looks great, no edits from me

**Comment by danemauland** [comment]
Re-opening since I closed the wrong issue. This looks really good. There's one major issue: your "Start the Really Smart Annotation" isn't showing up on firefox.

One other thing I noticed: the selected text doesn't stay highlighted after clicking the "Start the Really Smart Annotation" button. Add this feature to your MVP list as a bonus, but don't spend any time working on it right now.

**Comment by thedaebu** [comment]
It now opens up on Firefox.
For the window.getselection attributes, there is stuff for anchor/base(one end) and extent/focus(other end). Base and extent are readable for Chrome but not for Mozilla so I changed them to anchor and focus.

The username you had helped me.

You can now click in the blank area and the modal will now pop up.

**Comment by danemauland** [comment]
Fix bug as discussed then this should be done

**Comment by thedaebu** [comment]
I pushed the new version up. I used Math.min/Math.max instead of sort.

**Comment by danemauland** [comment]
Nice work!
